#!/bin/bash
pyfile=$PYFILE
pyfilec="${pyfile%.*}.pyc"
echo "Compiling $pyfile ..."
python -m py_compile "$pyfile"
mv "${pyfile}c" "$pyfilec"
length=$(od -t x1 "$pyfilec" | zgrep -c "Best School")
echo "$length"